services:

  dockerfile_2_service:
    environment:
      - ENV=local
    container_name: dockerfile_2
    image: dockerfile_2
    build:
      context: .
      dockerfile: ./Dockerfile_2
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  dockerfile_3_service:
    environment:
      - ENV=local
    container_name: dockerfile_3
    image: dockerfile_3
    build:
      context: .
      dockerfile: ./Dockerfile_3
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  dockerfile_4_service:
    environment:
      - ENV=local
    container_name: dockerfile_4
    image: dockerfile_4
    build:
      context: .
      dockerfile: ./Dockerfile_4
      target: my-app
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  test_dockerfile_4_service:
    environment:
      - ENV=local
    container_name: dockerfile_4
    image: dockerfile_4
    build:
      context: .
      dockerfile: ./Dockerfile_4
      target: my-app-dev
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3