services:
  api:
    environment:
      - ENV=local
    container_name: ddl_dockerfile_1
    image: ddl_dockerfile_1
    build:
      context: .
      dockerfile: ./Dockerfile_1
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider -q http://localhost:8000/ || exit 1"
        ]
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
