# syntax=docker/dockerfile:1
FROM python:3.12-alpine as python-base

ENV POETRY_VIRTUALENVS_IN_PROJECT=true \
    VENV_PATH="/.venv"

ENV PATH="$VENV_PATH/bin:$PATH"

RUN apk add poetry

COPY /poetry.lock /pyproject.toml ./
RUN poetry install

WORKDIR /api
COPY ./api .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
