# syntax=docker/dockerfile:1
FROM python:3.12-alpine AS python-base

ENV PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"
ENV PATH="$VENV_PATH/bin:$PATH"

RUN apk add curl

FROM python-base AS poetry-base
LABEL maintainer="You <your@email.com>"

ENV POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_VERSION=1.8.3 \
  POETRY_VIRTUALENVS_OPTIONS_NO_PIP=true \
  POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"

WORKDIR $PYSETUP_PATH
RUN --mount=type=cache,target=/root/.cache \
  curl -sSL https://install.python-poetry.org | python -

FROM poetry-base AS my-app
LABEL maintainer="You <your@email.com>"

WORKDIR /api
COPY /poetry.lock /pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache \
    poetry install --only main --no-directory -n    

COPY ./api .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


FROM my-app AS my-app-dev

RUN poetry install --only dev --no-root --no-directory -n

# ENTRYPOINT ["pytest", "--cov=app", "tests/"]