# syntax=docker/dockerfile:1
# Build with docker build -f Dockerfile_1 -t version_1 . --no-cache
# Run with docker run -p 8000:8000 version_1
FROM python:3.12-alpine AS my-app

ENV POETRY_VIRTUALENVS_IN_PROJECT=true \
    VENV_PATH="/.venv"

ENV PATH="$VENV_PATH/bin:$PATH"

COPY . .
RUN apk add poetry
RUN poetry install

WORKDIR /api
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
