# syntax=docker/dockerfile:1
# Build with docker build -f Dockerfile_1a -t version_1a . --no-cache
# Run with docker run -p 8000:8000 version_1a
FROM python:3.12-alpine AS my-app

ENV VENV_PATH="/.venv" \
    POETRY_VERSION=1.8.4 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VIRTUALENVS_OPTIONS_NO_PIP=true \
    POETRY_VIRTUALENVS_OPTIONS_NO_SETUPTOOLS=true

ENV PATH="$VENV_PATH/bin:$PATH"

COPY . .
RUN apk add --no-cache poetry
RUN poetry install --only main --no-root --no-directory -n

WORKDIR /api
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
